---
- name: Install and configure Nginx
  hosts: webservers
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
